const app = document.getElementById("app");
const KEY = "agentmanifest_workbench_v1";
const ranks = [
  ["L0", "Board", "A0"], ["L1", "CEO", "A1"], ["L2", "VP", "A2"],
  ["L3", "Director", "A3"], ["L4", "Manager", "A4"], ["L5", "IC", "A5"]
];
const scopeCategories = ["Customer data", "External communications", "Financial actions", "Production systems", "Analytics data", "Content publishing", "HR data", "Permission changes"];
const sensitiveTerms = ["ssn", "social security", "dob", "date of birth", "salary", "compensation", "payroll", "tax", "bank", "benefit", "medical", "disability", "race", "ethnicity", "gender", "veteran", "visa", "citizenship", "passport", "i-9"];
const aliases = {
  external_id: ["worker id", "employee id", "employee number", "worker"],
  email: ["primary work email", "work email", "email", "email address"],
  upn: ["upn", "user principal name", "username"],
  full_name: ["worker name", "employee name", "full name", "name", "display name"],
  job_title: ["business title", "job title", "position", "title", "job profile"],
  department: ["department", "dept", "team", "organization"],
  manager_external_id: ["manager id", "manager worker id", "supervisor id"],
  manager_email: ["manager email", "supervisor email", "reports to email"],
  manager_name: ["manager", "manager name", "supervisor", "reports to"],
  status: ["employment status", "worker status", "status"],
  management_level: ["management level", "job level", "level"],
  company: ["company", "legal entity"],
  business_unit: ["business unit", "division"],
  cost_center: ["cost center", "cost centre"],
  location: ["location", "work location", "office", "site", "region"]
};
let state = load();
function emptyState(){return {id:crypto.randomUUID(), step:"intake", mode:"", company:{company_name:"", hris_system:"Workday", identity_provider:"Microsoft Entra", primary_it_environment:"Microsoft", policy_version:"Discovery v1"}, headers:[], mappings:{}, dropped:[], rawRows:[], notes:"", humans:[], agents:[], issues:[], generated:null};}
function load(){try{return JSON.parse(localStorage.getItem(KEY)) || emptyState()}catch{return emptyState()}}
function save(){localStorage.setItem(KEY, JSON.stringify(state));}
function esc(v){return String(v ?? "").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));}
function clean(v){return String(v||"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();}
function slug(v){return clean(v).replace(/\s+/g,"-") || crypto.randomUUID();}
function split(v){return Array.isArray(v)?v:String(v||"").split(/[|;,]/).map(x=>x.trim()).filter(Boolean);}
function pct(n,d){return d?Math.round(n/d*100):0;}
function step(id){state.step=id; save(); render();}
function set(path, value){const [a,b]=path.split("."); state[a][b]=value; save(); render();}
function status(){const humans=state.humans.length, agents=state.agents.length; return {humans:humans?100:0, managers:pct(state.humans.filter(h=>h.manager_external_id||h.manager_email||["L0","L1"].includes(h.permission_rank)).length, humans), envelopes:pct(state.humans.filter(h=>h.permission_rank&&h.permission_scopes).length, humans), agents:pct(state.agents.filter(a=>a.owner_human_id||a.owner_email).length, agents), gaps:state.issues.filter(i=>!i.resolved).length};}
function render(){const s=status(); app.innerHTML=`<div class="shell"><header class="top"><b>Pedigree</b><span>AgentManifest Workbench</span><button onclick="loadDemo()">Demo</button><button onclick="resetAll()">Reset</button></header><nav>${["intake","company","import","permissions","agents","export"].map(x=>`<button class="${state.step===x?'on':''}" onclick="step('${x}')">${x}</button>`).join("")}</nav><main>${screen(s)}</main></div><div id="toast" class="toast"></div>`;}
function screen(s){if(state.step==="intake")return intake(); if(state.step==="company")return company(); if(state.step==="import")return importer(s); if(state.step==="permissions")return permissions(); if(state.step==="agents")return agents(); return exporter(s);}
function intake(){return `<h1>Build a Pedigree-ready discovery audit</h1><p class="lede">Start with a Workday-style CSV, a messy discovery transcript, manual entry, or all three. Each pass fills more gaps without breaking partial results.</p><div class="cards">${[["workday","Workday CSV"],["scratch","Start from scratch"],["hybrid","Messy hybrid"]].map(([id,label])=>`<button class="card ${state.mode===id?'selected':''}" onclick="state.mode='${id}';save();render()"><b>${label}</b><span>Iteratively discover humans, AI agents, manager chains, and permission ceilings.</span></button>`).join("")}</div><section class="rule">Agents inherit from humans. Agents never outrank humans. Agents never exceed human tool scopes. Exceptions require explicit approval.</section>`;}
function company(){return `<h1>Company profile</h1><div class="panel grid">${field("company.company_name","Company name")}${field("company.industry","Industry")}${field("company.hris_system","HRIS")}${field("company.identity_provider","Identity provider")}${field("company.primary_it_environment","IT environment")}${field("company.policy_version","Role policy")}</div>`;}
function field(path,label){const [a,b]=path.split(".");return `<label>${label}<input value="${esc(state[a][b])}" oninput="set('${path}',this.value)"></label>`;}
function importer(s){return `<h1>Import, parse, and close gaps</h1><div class="metrics">${metric("Humans",s.humans)}${metric("Manager links",s.managers)}${metric("Permission envelopes",s.envelopes)}${metric("Agent ownership",s.agents)}${metric("Open gaps",s.gaps,true)}</div><section class="panel"><h2>Workday-style CSV</h2><p>Upload/re-upload exports as discovery improves. Sensitive HR fields are dropped.</p><label class="btn">Upload CSV<input type="file" accept=".csv" hidden onchange="readCsv(this.files[0])"></label><button onclick="downloadTemplate()">Template</button>${state.headers.length?mappingTable():""}</section><section class="panel"><h2>Discovery transcript</h2><textarea placeholder="Paste notes: Sarah Chen is Marketing Manager reporting to David Kim. Sarah owns Content Drafter Agent for content publishing." oninput="state.notes=this.value;save()">${esc(state.notes)}</textarea><button onclick="parseNotes()">Parse notes into audit</button><button onclick="sampleNotes()">Sample notes</button></section>${issues()}${humansList()}`;}
function metric(label,value,bad){return `<div class="metric"><span>${label}</span><b class="${bad&&value?'bad':''}">${value}${bad?'':'%'}</b></div>`;}
function isSensitive(h){const x=clean(h); return sensitiveTerms.some(t=>x.includes(clean(t)));}
function inferMap(headers){const out={}; headers.forEach(h=>{if(isSensitive(h))return; const x=clean(h); for(const [key,vals] of Object.entries(aliases)){if(vals.some(v=>x===clean(v)||x.includes(clean(v)))){out[h]=key; break;}}}); return out;}
function mappingTable(){return `<h3>Column mapping</h3><div class="map">${state.headers.map(h=>`<div><b>${esc(h)}</b><select ${isSensitive(h)?"disabled":""} onchange="state.mappings['${h.replace(/'/g,"\\'")}']=this.value;normalize();"><option value="">Exclude</option>${Object.keys(aliases).map(k=>`<option ${state.mappings[h]===k?'selected':''}>${k}</option>`).join("")}</select><span>${isSensitive(h)?"Sensitive - dropped":state.mappings[h]||"Excluded"}</span></div>`).join("")}</div><button onclick="normalize()">Normalize rows</button>`;}
function readCsv(file){if(!file)return; const r=new FileReader(); r.onload=()=>{state.rawRows=parseCsv(r.result); state.headers=Object.keys(state.rawRows[0]||{}); state.mappings=inferMap(state.headers); state.dropped=state.headers.filter(isSensitive); normalize();}; r.readAsText(file);}
function parseCsv(text){const rows=text.trim().split(/\r?\n/).filter(Boolean).map(l=>l.split(/,(?=(?:(?:[^"]*"){2})*[^"]*$)/).map(c=>c.replace(/^"|"$/g,"").trim())); const head=rows.shift()||[]; return rows.map(cols=>Object.fromEntries(head.map((h,i)=>[h,cols[i]||""])));}
function normalize(){state.rawRows.forEach((row,i)=>upsertHuman(normalizeHuman(row,i))); derive(); detect(); save(); render();}
function normalizeHuman(row,i){const h={id:crypto.randomUUID(),source:"workday",raw_index:i+1}; Object.entries(state.mappings).forEach(([col,key])=>h[key]=row[col]||""); h.email=(h.email||"").toLowerCase(); h.upn=(h.upn||h.email||"").toLowerCase(); h.full_name=h.full_name||[h.first_name,h.last_name].filter(Boolean).join(" "); h.external_id=h.external_id||h.email||`row-${i+1}`; h.status=normStatus(h.status); return h;}
function normStatus(v){v=clean(v||"active"); if(v.includes("term")||v.includes("inactive"))return"terminated"; if(v.includes("leave"))return"on_leave"; return"active";}
function upsertHuman(h){const key=clean(h.email||h.external_id||h.full_name); const old=state.humans.find(x=>clean(x.email||x.external_id||x.full_name)===key); if(old)Object.assign(old,h,{id:old.id}); else state.humans.push(h);}
function parseNotes(){const lines=state.notes.split(/\r?\n|[.;]\s+/).map(x=>x.trim()).filter(Boolean); lines.forEach((line,i)=>{const h=parseHuman(line,i); if(h)upsertHuman(h); const a=parseAgent(line); if(a)state.agents.push(a);}); linkManagers(); derive(); detect(); save(); render();}
function parseHuman(line,i){const name=(line.match(/^([A-Z][a-z]+(?:\s+[A-Z][a-z]+){1,3})\s+(?:is|serves as|works as)/)||[])[1]; if(!name||/agent/i.test(name))return null; const title=(line.match(/(?:is|serves as|works as)\s+(?:the\s+)?([^,]+?)(?:\s+in\s+|\s+and reports|\s+reporting|$)/i)||[])[1]||""; const dept=(line.match(/\bin\s+([A-Z][A-Za-z &]+?)(?:\s+and reports|\s+reporting|$)/i)||[])[1]||deptFrom(title); const manager=(line.match(/reports to\s+([A-Z][a-z]+(?:\s+[A-Z][a-z]+){1,3})/i)||line.match(/reporting to\s+([A-Z][a-z]+(?:\s+[A-Z][a-z]+){1,3})/i)||[])[1]||""; return {id:crypto.randomUUID(),source:"discovery_notes",external_id:`notes-${slug(name)}`,email:"",upn:"",full_name:name,job_title:title,department:dept,manager_name:manager,status:"active"};}
function parseAgent(line){if(!/agent/i.test(line)||!/owns|controls|owned by/i.test(line))return null; const ownerName=(line.match(/^([A-Z][a-z]+(?:\s+[A-Z][a-z]+){0,3})\s+(?:owns|controls)/i)||line.match(/owned by\s+([A-Z][a-z]+(?:\s+[A-Z][a-z]+){1,3})/i)||[])[1]||""; const name=(line.match(/(?:owns|controls)\s+(.+?Agent)\b/i)||line.match(/^(.+?Agent)\s+(?:is\s+)?owned by/i)||[])[1]||""; if(!name)return null; const owner=state.humans.find(h=>clean(h.full_name)===clean(ownerName)); const scopes=scopeCategories.filter(s=>clean(line).includes(clean(s))); return {agent_id:crypto.randomUUID(),agent_name:name,owner_human_id:owner?.id||"",owner_name:owner?.full_name||ownerName,owner_email:owner?.email||"",department:owner?.department||"",purpose:line,requested_scopes:scopes.length?scopes:["Analytics data"],actions_capable:/external|email/i.test(line)?["send_external_email"]:/financial|payment|money/i.test(line)?["move_money"]:["read_only"],risk:/financial|payment|production|permission|external/i.test(line)?"high":"medium"};}
function deptFrom(title){const t=clean(title); if(t.includes("market"))return"Marketing"; if(t.includes("finance")||t.includes("payment"))return"Finance"; if(t.includes("sales"))return"Sales"; if(t.includes("hr")||t.includes("people"))return"HR"; if(t.includes("security")||t.includes("engineer")||t.includes("technology"))return"IT"; return"";}
function linkManagers(){state.humans.forEach(h=>{if(h.manager_name&&!h.manager_external_id&&!h.manager_email){const m=state.humans.find(x=>clean(x.full_name)===clean(h.manager_name)); if(m){h.manager_external_id=m.external_id; h.manager_email=m.email;}}}); state.agents.forEach(a=>{const o=state.humans.find(h=>h.email===a.owner_email||clean(h.full_name)===clean(a.owner_name)); if(o){a.owner_human_id=o.id; a.owner_email=o.email; a.department=o.department;}});}
function derive(){state.humans.forEach(h=>{const r=rankFor(h); const def=ranks.find(x=>x[0]===r)||ranks[5]; h.permission_rank=def[0]; h.permission_label=def[1]; h.max_agent_rank=def[2]; h.permission_scopes=scopesFor(h);}); linkManagers();}
function rankFor(h){const t=clean(`${h.management_level||""} ${h.job_title||h.title||""}`); if(t.includes("board"))return"L0"; if(t.includes("chief")||t.includes("ceo")||t.includes("cfo")||t.includes("cio"))return"L1"; if(t.includes("vp")||t.includes("vice president"))return"L2"; if(t.includes("director"))return"L3"; if(t.includes("manager")||t.includes("lead")||t.includes("head"))return"L4"; return"L5";}
function scopesFor(h){const text=`${h.department||""} ${h.job_title||h.title||""}`; const s={business_scope:[h.department,h.business_unit,h.cost_center,h.location].filter(Boolean),allowed_categories:["Analytics data","Content publishing"],approval_required:["Customer data","External communications"],blocked:["Production systems"]}; /finance|accounting|procurement/i.test(text)?s.approval_required.push("Financial actions"):s.blocked.push("Financial actions"); /hr|people|talent/i.test(text)?s.approval_required.push("HR data"):s.blocked.push("HR data"); /it|security|engineering|technology/i.test(text)?s.approval_required.push("Permission changes"):s.blocked.push("Permission changes"); return s;}
function detect(){const ids=new Set(), emails=new Set(); state.issues=[]; state.humans.forEach(h=>{if(!h.email)gap(h,"missing_email",`Add work email/UPN for ${h.full_name||h.external_id}`,true); if(!h.full_name)gap(h,"missing_name",`Add display name for ${h.external_id}`,true); if(!h.department)gap(h,"missing_department",`Add department for ${h.full_name||h.external_id}`,false); if(!h.manager_external_id&&!h.manager_email&&!h.manager_name&&!["L0","L1"].includes(h.permission_rank))gap(h,"missing_manager",`Add manager for ${h.full_name||h.external_id}`,true); if(ids.has(h.external_id))gap(h,"duplicate_id",`Resolve duplicate worker id ${h.external_id}`,true); if(h.email&&emails.has(h.email))gap(h,"duplicate_email",`Resolve duplicate email ${h.email}`,true); ids.add(h.external_id); emails.add(h.email);}); state.dropped.forEach(c=>state.issues.push({type:"sensitive_column",question:`Sensitive field dropped: ${c}`,detail:"Excluded from manifest.",resolved:true}));}
function gap(h,type,question,blocking){state.issues.push({human_id:h.id,type,question,blocking,resolved:false});}
function issues(){return state.issues.length?`<section class="panel"><h2>Gaps and cleanup questions</h2>${state.issues.map((i,n)=>`<div class="issue"><b>${esc(i.question)}</b><span>${i.blocking?'Blocking':'Advisory'}</span><button onclick="state.issues[${n}].resolved=true;save();render()">Resolve</button></div>`).join("")}</section>`:"";}
function humansList(){return state.humans.length?`<section class="panel"><h2>Normalized humans</h2>${state.humans.map(h=>`<div class="person"><b>${esc(h.full_name||'Unknown')}</b><span>${esc(h.job_title||h.title||'No title')} · ${esc(h.department||'No department')} · ${esc(h.permission_rank||'Unranked')}</span></div>`).join("")}</section>`:"";}
function permissions(){if(!state.humans.length)return`<h1>Permission ceiling</h1><p>Import or add humans first.</p>`; const h=state.humans[0]; const owned=state.agents.filter(a=>a.owner_human_id===h.id||a.owner_email===h.email); return `<h1>Org Rank and Permission Ceiling</h1><div class="permission"><aside><h2>${esc(h.full_name)}</h2><p>Human rank: <b>${h.permission_rank} ${h.permission_label}</b></p><p>Agent max rank: <b>${h.max_agent_rank}</b></p><p>Rule: Agents cannot exceed this human's scopes.</p></aside><section><h2>Hierarchy</h2>${chainFor(h).reverse().map(x=>`<div class="node ${x.id===h.id?'focus':''}">${esc(x.full_name)}<span>${esc(x.job_title||x.title||'')}</span></div>`).join("")}${owned.map(a=>`<div class="agentnode">${esc(a.agent_name)}<span>Child of ${esc(h.full_name)}</span></div>`).join("")}</section><section><h2>Ceiling summary</h2>${scopeCategories.map(c=>`<div class="ceiling"><b>${c}</b><span>${ceiling(h,c)}</span></div>`).join("")}</section></div><section class="rule">Agents inherit from human. Agents never outrank human. Exceptions require explicit approval.</section>`;}
function chainFor(h){const out=[h]; let cur=h; const seen=new Set([h.id]); while(cur.manager_external_id||cur.manager_email){const m=state.humans.find(x=>x.external_id===cur.manager_external_id||x.email===cur.manager_email); if(!m||seen.has(m.id))break; out.push(m); seen.add(m.id); cur=m;} return out;}
function ceiling(h,c){const s=h.permission_scopes||{}; if((s.blocked||[]).includes(c))return"Blocked"; if((s.approval_required||[]).includes(c))return"Approval required"; return"Allowed";}
function agents(){return `<h1>AI agents</h1><section class="panel"><button onclick="addAgent()">Add agent</button><label class="btn">Upload Agent CSV<input type="file" accept=".csv" hidden onchange="readAgents(this.files[0])"></label></section>${state.agents.map(a=>`<div class="itemCard"><div><b>${esc(a.agent_name)}</b><span>${esc(a.owner_name||a.owner_email||'No owner')} · ${esc((a.requested_scopes||[]).join(', '))} · ${fit(a)}</span></div></div>`).join("")}`;}
function addAgent(){const h=state.humans[0]||{}; state.agents.push({agent_id:crypto.randomUUID(),agent_name:"New Agent",owner_human_id:h.id||"",owner_name:h.full_name||"",owner_email:h.email||"",department:h.department||"",purpose:"",requested_scopes:["Analytics data"],actions_capable:["read_only"],risk:"medium"}); save(); render();}
function readAgents(file){if(!file)return; const r=new FileReader(); r.onload=()=>{parseCsv(r.result).forEach(row=>state.agents.push({agent_id:crypto.randomUUID(),agent_name:row.agent_name||row.name||"Unnamed Agent",owner_name:row.owner_name||"",owner_email:(row.owner_email||row.email||"").toLowerCase(),department:row.department||"",purpose:row.purpose||"",requested_scopes:split(row.requested_scopes||row.systems_touched),actions_capable:split(row.actions_capable),risk:row.risk||"medium"})); linkManagers(); save(); render();}; r.readAsText(file);}
function fit(a){const h=state.humans.find(x=>x.id===a.owner_human_id||x.email===a.owner_email); if(!h)return"Orphaned"; return (a.requested_scopes||[]).some(s=>ceiling(h,s)==="Blocked")?"Exceeds parent ceiling":"Inside parent ceiling";}
function exporter(s){return `<h1>Manifest export</h1><div class="metrics">${metric("Humans",s.humans)}${metric("Manager links",s.managers)}${metric("Agent ownership",s.agents)}${metric("Open gaps",s.gaps,true)}</div><section class="panel"><p>Partial results are allowed. Open gaps are exported as evidence so another discovery session can fill them later.</p><button onclick="generateManifest()">Generate Manifest</button><button ${state.generated?'':'disabled'} onclick="downloadManifest()">Download JSON</button><button ${state.generated?'':'disabled'} onclick="downloadBundle()">Download ZIP</button></section>${state.generated?`<pre>${esc(JSON.stringify(state.generated.pedigree_import.demo_summary,null,2))}</pre>`:""}`;}
async function generateManifest(){derive(); detect(); const now=new Date().toISOString(), tenant=slug(state.company.company_name||"discovery-tenant"); const humans=state.humans.map(h=>({human_id:h.id,tenant_id:tenant,external_id:h.external_id,email:h.email||"",full_name:h.full_name||"Unknown Human",department:h.department||null,job_title:h.job_title||h.title||null,status:["active","terminated","on_leave"].includes(h.status)?h.status:"active",manager_id:(state.humans.find(m=>m.external_id===h.manager_external_id||m.email===h.manager_email)||{}).id||null,entitlements:entitlements(h),created_at:now})); const agents=state.agents.map(a=>{const o=state.humans.find(h=>h.id===a.owner_human_id||h.email===a.owner_email); return {agent_id:a.agent_id,tenant_id:tenant,external_id:a.agent_id,platform:"custom",name:a.agent_name,description:a.purpose||null,status:o?"active":"orphaned",owner_human_id:o?.id||null,scope_snapshot:{knowledge_sources:a.requested_scopes||[],actions:a.actions_capable||[],environment_id:"agentmanifest-discovery",requested_scopes:a.requested_scopes||[],parent_fit:fit(a)},risk_score:risk(a),created_at:now};}); const manifest={manifest_version:"1.1",manifest_id:crypto.randomUUID(),generated_at:now,workspace_id:state.id,company:state.company,intake_mode:state.mode,hris_import:{source_system:state.company.hris_system||"Workday",source_rows:state.rawRows.length,accepted_columns:state.headers.filter(h=>state.mappings[h]&&!isSensitive(h)),dropped_sensitive_columns:state.dropped,unresolved_issue_count:state.issues.filter(i=>!i.resolved).length},humans:state.humans,reporting_relationships:state.humans.filter(h=>h.manager_external_id||h.manager_email).map(h=>({human_external_id:h.external_id,human_email:h.email,manager_external_id:h.manager_external_id,manager_email:h.manager_email})),permission_envelopes:state.humans.map(h=>({human_external_id:h.external_id,email:h.email,rank:h.permission_rank,label:h.permission_label,max_agent_rank:h.max_agent_rank,scopes:h.permission_scopes})),agents:state.agents.map(a=>({...a,fit:fit(a)})),pedigree_import:{dashboard_contract:"pedigree4-mvp-demo",endpoints:["/v1/demo/summary","/v1/humans","/v1/agents"],humans,agents,demo_summary:{tenant,humans:humans.length,agents:agents.length,orphaned_agents:agents.filter(a=>a.status==="orphaned").length,high_risk_agents:agents.filter(a=>a.risk_score>=70).length,policies:3}},governance:{rule:"Agents inherit from humans. Agents never outrank humans. Agents never exceed human tool scopes. Exceptions require explicit approval."},data_quality:{issues:state.issues,blocking_open:state.issues.filter(i=>i.blocking&&!i.resolved).length}}; manifest.signature={algorithm:"sha256",hash:await sha(JSON.stringify(manifest)),signed_at:now}; state.generated=manifest; save(); render();}
function entitlements(h){const s=h.permission_scopes||{}; return [`rank:${h.permission_rank||"L5"}`,...(s.business_scope||[]).map(x=>`scope:${x}`),...(s.allowed_categories||[]).map(x=>`allow:${x}`),...(s.approval_required||[]).map(x=>`approval:${x}`)];}
function risk(a){let n=20; if(fit(a)==="Orphaned")n+=45; if(fit(a)==="Exceeds parent ceiling")n+=35; if(a.risk==="high")n+=20; if((a.actions_capable||[]).some(x=>/money|delete|permission|external/i.test(x)))n+=20; return Math.min(100,n);}
async function sha(s){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s)); return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("");}
function downloadManifest(){download("pedigree_manifest.json",JSON.stringify(state.generated,null,2),"application/json");}
function downloadBundle(){download("pedigree_bundle.json",JSON.stringify(state.generated,null,2),"application/json");}
function downloadTemplate(){download("workday_template.csv","Worker ID,Full Name,Primary Work Email,Business Title,Department,Manager ID,Manager Name,Manager Email,Employment Status,Management Level,Location\n","text/csv");}
function download(name,body,type){const a=document.createElement("a"); a.href=URL.createObjectURL(new Blob([body],{type})); a.download=name; a.click(); setTimeout(()=>URL.revokeObjectURL(a.href),100);}
function sampleNotes(){state.notes="Sarah Chen is the Marketing Manager in Marketing and reports to David Kim. Sarah owns Content Drafter Agent for content publishing and analytics data. David Kim is VP Marketing and reports to Maya Ross. Omar Patel is Finance Manager in Finance reporting to Priya Shah. Omar owns Payment Exception Agent for financial actions."; save(); render();}
function loadDemo(){state=emptyState(); state.mode="hybrid"; state.company={company_name:"Apex Industrial Group",hris_system:"Workday",identity_provider:"Microsoft Entra",primary_it_environment:"Microsoft",policy_version:"Discovery v1"}; state.notes="Sarah Chen is the Marketing Manager in Marketing and reports to David Kim. Sarah owns Content Drafter Agent for content publishing and analytics data. Sarah owns Brand Voice Checker for external communications. David Kim is VP Marketing and reports to Maya Ross. Omar Patel is Finance Manager in Finance reporting to Priya Shah. Omar owns Payment Exception Agent for financial actions."; parseNotes();}
function resetAll(){localStorage.removeItem(KEY); state=emptyState(); render();}
function toast(msg){const t=document.getElementById("toast"); if(t){t.textContent=msg; t.classList.add("show"); setTimeout(()=>t.classList.remove("show"),1500)}}
render();
